"""empty message

Revision ID: aad04be500a2
Revises: e33e09c18fbd
Create Date: 2021-06-12 17:09:42.753351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad04be500a2'
down_revision = 'e33e09c18fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manage', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manage', 'users', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manage', type_='foreignkey')
    op.drop_column('manage', 'goal_id')
    # ### end Alembic commands ###
