"""empty message

Revision ID: d1238083c9d5
Revises: fed53042427e
Create Date: 2021-06-12 16:22:39.167458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1238083c9d5'
down_revision = 'fed53042427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('tags', sa.String(length=100), nullable=True))
    op.add_column('goals', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('goals', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('goals', 'end_date')
    op.drop_column('goals', 'start_date')
    op.drop_column('goals', 'tags')
    # ### end Alembic commands ###
