"""empty message

Revision ID: ef31e9fec04c
Revises: aad04be500a2
Create Date: 2021-06-12 17:12:10.037459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef31e9fec04c'
down_revision = 'aad04be500a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'])
    op.drop_constraint('manage_goal_id_fkey', 'manage', type_='foreignkey')
    op.create_foreign_key(None, 'manage', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manage', type_='foreignkey')
    op.create_foreign_key('manage_goal_id_fkey', 'manage', 'users', ['goal_id'], ['id'])
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'user_id')
    # ### end Alembic commands ###
